sudo: required

services:
  - docker


before_install:
  - docker build -t aontimer/mxshop3 .
  - echo "jmdjsj903291A" | docker login -u "aontimer" --password-stdin
  - docker push aontimer/mxshop3

script:
  - echo "a"